### ISSUE TITLE
English version of PTT

### ISSUE THREAD

**Issue by billsimon** [ptt/pttbbs#29]
I am interested in an English version of PTT, for use in primarily English speaking areas.

Has anyone done a translation? Or is there interest in doing a translation?

**Comment by chhsiao1981** [comment]
hi @billsimon,

Unsure whether your question is about the system-setup or about the content of ptt.

For system-setup:
   ptt is a kind of BBS-system and is an open-source project.
   I (And all the system-admins) can try to provide the English version of the document to help you setup your own ptt-like BBS.

For content:
   I am sorry that it's a very hard problem (involving natural-language processing) and I don't think ptt can provide such service in the near future.

**Comment by billsimon** [comment]
Hello @chhsiao1981! Thanks for your quick response.

I mean to do translation of documentation so that English speakers can set up a PTT-like BBS.

Also to translate the strings within the BBS software so that it can be deployed in an English-speaking region. I do not mean live automatic translation of content. 

It looks like the software works with UTF8 terminals which would be suitable for all character sets.

**Comment by chhsiao1981** [comment]
hi @billsimon,

I am sorry that It's with high probability that I myself am unable to do the translation before 11/20.
Hopefully you can wait until some time after 11/20.

Due to the original purpose of ptt (developed 15 years ago), currently there are some caveats:

1. mainly used in telnet / ssh protocol, currently web-interface is used only for reading articles, no other interactions.

2. efficiency comes with highly optimized local shm / local file-distribution in 1 machine.
     (Such kind of service is write-less-read-a-lot service, ptt use RAID as large local-file-storage.)
     unable to do horizontally scaling for now.

3. Originally designed for big-5. UTF-8 loses the "two-color-in-1-char" effect in terminal.
     (But I don't think the change impact a lot, considering that many people also read the articles from browsers nowadays.)

4. Timezone is fixed in GMT+8, but you can definitely modify the code or pr the code.

     https://github.com/ptt/pttbbs/blob/master/common/diet/time.c

5. (Some other caveats that I don't know for now～)

**Comment by billsimon** [comment]
I am not in a hurry and you are of course not obligated to answer my request; I am grateful that you are willing to consider it. Thank you.

**Comment by chhsiao1981** [comment]
The English version of the installation-guide is described in the [wiki](https://github.com/ptt/pttbbs/wiki/INSTALL-en). I think we can close the issue～
